[package]
name = "cosmic-bg-core"
version = "0.1.0"
edition = "2021"

[dependencies]
smithay-client-toolkit = "0.20.0"
wayland-client = "0.31.12"
gstreamer = "0.23"
gstreamer-app = "0.23"
gstreamer-video = "0.23"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"

wayland-protocols = { version = "0.32", features = ["client"] }
wayland-protocols-wlr = { version = "0.3", features = ["client"] }